import React from 'react';

export const mockCurrentUser = {
    id: 'user-1',
    name: 'Test User',
    avatar: '/avatar.jpg',
    coverImage: '/cover.jpg',
    title: 'Tester',
    bio: 'Bio',
    institution: 'Test Inst',
    location: 'Test Loc',
    connections: [],
    profileViews: 10,
    citations: 5,
    skills: ['Skill 1'],
    researchInterests: ['Interest 1'],
    experience: [],
    education: [],
    publications: [],
    projects: [],
    gallery: []
};

export const mockContextValue = {
    currentUser: mockCurrentUser,
    updateCurrentUser: jest.fn(),
    posts: [],
    addPost: jest.fn(),
    updatePost: jest.fn(),
    deletePost: jest.fn(),
    likePost: jest.fn(),
    addComment: jest.fn(),
    deleteComment: jest.fn(),
    savedPosts: [],
    toggleSavePost: jest.fn(),
    notifications: [],
    markNotificationRead: jest.fn(),
    markAllNotificationsRead: jest.fn(),
    connectionRequests: [],
    sendConnectionRequest: jest.fn(),
    acceptConnectionRequest: jest.fn(),
    rejectConnectionRequest: jest.fn(),
    withdrawConnectionRequest: jest.fn(),
    removeConnection: jest.fn(),
    allUsers: [],
    searchQuery: '',
    setSearchQuery: jest.fn(),
    conversations: [],
    messages: [],
    sendMessage: jest.fn(),
    addExperience: jest.fn(),
    updateExperience: jest.fn(),
    deleteExperience: jest.fn(),
    addEducation: jest.fn(),
    updateEducation: jest.fn(),
    deleteEducation: jest.fn(),
    addPublication: jest.fn(),
    updatePublication: jest.fn(),
    deletePublication: jest.fn(),
    addProject: jest.fn(),
    updateProject: jest.fn(),
    deleteProject: jest.fn(),
    addToGallery: jest.fn(),
    removeFromGallery: jest.fn(),
    isCreatePostOpen: false,
    editingPost: null,
    openCreatePost: jest.fn(),
    closeCreatePost: jest.fn(),
};
